# @package _global_
defaults:
  - _self_
  - data: sonics
  - model: bimamba
  - logger: wandb
  - trainer: default

cpk_path: /net/people/plgrid/plgjedrzejkusnierz/big_storage/SVDD/outputs/2026-06-04/16-49-45/late-fusion-small-model-last-vector-aggregation/checkpoints/epoch=018-val_loss=0.0000.ckpt