# @package _global_
defaults:
  - _self_
  - data: sonics
  - model: bimamba
  - logger: wandb
  - trainer: default

cpk_path: /net/people/plgrid/plgjedrzejkusnierz/big_storage/SVDD/outputs/2026-04-17/10-33-36/checkpoints/epoch_epoch=005.ckpt
