defaults:
  - _self_
  - preprocessing: sonics

paths:
  input_dir: /net/people/plgrid/plgjedrzejkusnierz/scratch/data/Sonics/all_data
  output_dir: /net/people/plgrid/plgjedrzejkusnierz/scratch/data/Sonics/preprocessed_test