# src/configs/preprocessing/m6.yaml
_target_: preprocessing.two_class_dir.TwoClassDirPreprocessor
deepfake_dir: /net/people/plgrid/plgjedrzejkusnierz/scratch/data/M6/M6_16k/ai
bonafide_dir: /net/people/plgrid/plgjedrzejkusnierz/scratch/data/M6/M6_16k/human
extensions: [".wav"]
sample_rate: 16000
total_len_sec: 120
chunk_len_sec: 30
batch_size: 4
num_workers: 4
wav2vec_model_name: facebook/wav2vec2-xls-r-300m
mert_model_name: m-a-p/MERT-v1-330M
lowpass_cutoff_hz: null
limit_files: null
output_dir: /net/people/plgrid/plgjedrzejkusnierz/scratch/data/M6/m6_preprocessed
